[Journal]
SystemMaxUse=200M
SystemKeepFree=1G
SystemMaxFileSize=16M
RuntimeMaxUse=16M
RuntimeMaxFileSize=4M
MaxFileSec=1day
MaxRetentionSec=14day
Compress=yes
RateLimitIntervalSec=30s
RateLimitBurst=1000
