/home/crawler/logs/*.log /home/crawler/logs/*/*.log {
    su root root
    missingok
    notifempty
    daily
    maxsize 20M
    rotate 5
    maxage 14
    compress
    compressoptions -1
    delaycompress
    copytruncate
}
