# Generated by Django 5.1 on 2024-10-26 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolnjoy', '0003_coolnjoydeal_cool_n_joy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolnjoydeal',
            name='crawled_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 5, 57, 52, 336087), verbose_name='수집일'),
        ),
        migrations.AlterField(
            model_name='coolnjoydeal',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 5, 57, 52, 336067), verbose_name='생성일'),
        ),
    ]
