# Generated by Django 5.1 on 2024-10-26 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolnjoy', '0004_alter_coolnjoydeal_crawled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolnjoydeal',
            name='crawled_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 10, 30, 36, 883073), verbose_name='수집일'),
        ),
        migrations.AlterField(
            model_name='coolnjoydeal',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 10, 30, 36, 883050), verbose_name='생성일'),
        ),
    ]
