# Generated by Django 5.1 on 2024-10-26 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolnjoy', '0005_alter_coolnjoydeal_crawled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolnjoydeal',
            name='crawled_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 13, 3, 53, 289277), verbose_name='수집일'),
        ),
        migrations.AlterField(
            model_name='coolnjoydeal',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 13, 3, 53, 289255), verbose_name='생성일'),
        ),
    ]
