# Generated by Django 5.1 on 2025-12-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NOTICE', '공지'), ('NORMAL', '일반')], default='NORMAL', max_length=32),
        ),
    ]
