# Generated by Django 5.1 on 2025-12-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0005_deal_write_at_alter_deal_create_at'),
        ('user', '0012_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='크롤링 일자')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='업데이트일시')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'favorite_deals',
            },
        ),
    ]
