# Generated by Django 5.1 on 2024-10-26 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppomppu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppomppudeal',
            name='a_link',
        ),
        migrations.RemoveField(
            model_name='ppomppudeal',
            name='a_link2',
        ),
        migrations.RemoveField(
            model_name='ppomppudeal',
            name='b_link',
        ),
        migrations.RemoveField(
            model_name='ppomppudeal',
            name='cool_n_joy_id',
        ),
        migrations.RemoveField(
            model_name='ppomppudeal',
            name='img',
        ),
        migrations.RemoveField(
            model_name='ppomppudeal',
            name='url',
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='article_id',
            field=models.BigIntegerField(default=0, verbose_name='글아이디'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='배송료'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='dislike_count',
            field=models.IntegerField(default=0, verbose_name='비추수'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='종료여부'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='origin_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='원글주소'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='shop_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='쇼핑몰이름'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='shop_url_1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='쇼핑몰 링크'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='썸네일'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 10, 30, 36, 832186), verbose_name='업데이트일시'),
        ),
        migrations.AddField(
            model_name='ppomppudeal',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='content',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='본문내용'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='crawled_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 10, 30, 36, 832192), verbose_name='크롤링 수집일'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 10, 30, 36, 832170), verbose_name='원글 작성일'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='subject',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='제목'),
        ),
    ]
