# Generated by Django 5.1 on 2024-10-26 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppomppu', '0003_alter_ppomppudeal_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppomppudeal',
            name='content',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='본문내용'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='crawled_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 13, 6, 34, 678399), verbose_name='크롤링 수집일'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 13, 6, 34, 678379), verbose_name='원글 작성일'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 13, 6, 34, 678393), verbose_name='업데이트일시'),
        ),
    ]
