# Generated by Django 5.1 on 2024-10-28 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppomppu', '0004_alter_ppomppudeal_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppomppudeal',
            name='crawled_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 48, 41, 645274), verbose_name='크롤링 수집일'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 48, 41, 645253), verbose_name='원글 작성일'),
        ),
        migrations.AlterField(
            model_name='ppomppudeal',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 48, 41, 645268), verbose_name='업데이트일시'),
        ),
    ]
