"""Reviewed teaching pairs, including constructed counterexamples; not a production accuracy sample."""
# Each family explicitly declares equivalent offers and a different product.
# The initial labels were reviewed during implementation, not generated by the local model.
FAMILIES = [
    ('코카콜라 제로 355ml 24캔','코카콜라 제로 355ml 48캔','코카콜라 제로 500ml 24캔'),
    ('코카콜라 오리지널 300ml 24개','코카콜라 오리지널, 300ml, 24개','코카콜라 제로 300ml 24개'),
    ('펩시콜라 제로슈거 라임 310ml 48캔','펩시콜라 제로슈거 라임 310ml 48캔 (19,950원/무료)','펩시콜라 제로슈거 라임 355ml 48캔'),
    ('햇반 210g 24개','햇반 210g 48개','햇반 현미밥 210g 24개'),
    ('삼성 990 PRO 1TB','[네이버] 삼성 990 PRO 1TB (120,000원/무료)','삼성 990 PRO 2TB'),
    ('삼성 980 PRO 1TB','삼성 980 PRO 1TB 특가','삼성 990 PRO 1TB'),
    ('AMD 9800X3D','[쿠팡] AMD 9800X3D 무료배송','AMD 7800X3D'),
    ('LG 27GP850','LG 27GP850 모니터','LG 27GR850'),
    ('로지텍 MX Master 4 무선 블루투스 마우스','직구 로지텍 MX Master 4 무선 블루투스 마우스','로지텍 MX Master 3S 무선 블루투스 마우스'),
    ('스타벅스 카페모카 270mlx10개','스타벅스 카페모카 270ml 20개','스타벅스 카페라떼 270ml 10개'),
    ('오뚜기 짜슐랭 145g 15개','오뚜기 짜슐랭 145g 30개','오뚜기 진라면 120g 15개'),
    ('삼성 갤럭시 S25 256GB','[지마켓] 삼성 갤럭시 S25 256GB 자급제','삼성 갤럭시 S25 512GB'),
    ('애플 아이폰 17 프로 512GB','[쿠팡] 애플 아이폰 17 프로 512GB 무료배송','애플 아이폰 17 프로맥스 512GB'),
    ('아디다스 갤럭시 8 블랙','아디다스 갤럭시 8 블랙 특가','아디다스 갤럭시 8 화이트'),
    ('나이키 에어포스 1 270mm','[네이버] 나이키 에어포스 1 270mm 무료배송','나이키 에어포스 1 280mm'),
    ('크리넥스 울트라클린 30m 30롤','크리넥스 울트라클린 30m 60롤','크리넥스 울트라클린 25m 30롤'),
]


def examples():
    for target,equivalent,different in FAMILIES:
        yield {'left_title':equivalent,'right_title':target,'same_product':True}
        yield {'left_title':'[쇼핑몰] '+target+' 무료배송','right_title':target,'same_product':True}
        yield {'left_title':different,'right_title':target,'same_product':False}
        yield {'left_title':'[쇼핑몰] '+different+' 특가','right_title':target,'same_product':False}


def install():
    from django.db import transaction
    from .jobs import add_example
    with transaction.atomic():
        for row in examples():
            add_example(row['left_title'],row['right_title'],row['same_product'],
                origin='bootstrap_review',actor='initial_pair_review_20260919')
    return len(list(examples()))
