# Generated by Django 5.1 on 2024-10-28 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.BigIntegerField(default=0, verbose_name='글아이디')),
                ('community_name', models.CharField(default='', max_length=64, verbose_name='커뮤니티명')),
                ('origin_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='원글주소')),
                ('shop_url_1', models.URLField(blank=True, max_length=512, null=True, verbose_name='쇼핑몰 링크1')),
                ('shop_url_2', models.URLField(blank=True, max_length=512, null=True, verbose_name='쇼핑몰 링크2')),
                ('shop_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='쇼핑몰이름')),
                ('thumbnail', models.URLField(blank=True, max_length=512, null=True, verbose_name='썸네일')),
                ('subject', models.CharField(blank=True, max_length=512, null=True, verbose_name='제목')),
                ('category', models.CharField(blank=True, max_length=32, null=True, verbose_name='카테고리')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('delivery_price', models.IntegerField(default=0, verbose_name='배송료')),
                ('recommend_count', models.IntegerField(default=0, verbose_name='추천수')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='비추수')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 48, 41, 723925), verbose_name='원글 작성일')),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 48, 41, 723932), verbose_name='업데이트일시')),
                ('crawled_at', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 48, 41, 723937), verbose_name='크롤링 수집일')),
                ('is_end', models.BooleanField(default=False, verbose_name='종료여부')),
            ],
            options={
                'db_table': 'deals',
            },
        ),
    ]
