# Generated by Django 5.1 on 2024-10-28 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='article_id',
            field=models.CharField(default=0, verbose_name='글아이디'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='crawled_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 55, 5, 81289), verbose_name='크롤링 수집일'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 55, 5, 81273), verbose_name='원글 작성일'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 13, 55, 5, 81283), verbose_name='업데이트일시'),
        ),
    ]
