# Generated by Django 5.1 on 2024-11-24 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='write_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0), verbose_name='원글 작성일'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='크롤링 일자'),
        ),
    ]
