# Generated by Django 5.1 on 2026-01-18 10:38

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_trgm_hash_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='subject_trgm_vector',
            field=pgvector.django.vector.VectorField(dimensions=1024, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['subject_trgm_vector'], m=16, name='hotdeal_subject_trgm_vec_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
