# Generated by Django 5.1 on 2026-09-17 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


REQUEST_TRIGGER = migrations.RunSQL(
            sql="""
CREATE FUNCTION public.enqueue_deal_classification() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$
BEGIN
    IF TG_OP='UPDATE' AND NEW.subject IS NOT DISTINCT FROM OLD.subject THEN RETURN NEW; END IF;
    INSERT INTO public.deal_classifications AS c
        (deal_id,input_title,category,candidate,status,source,manual_override,title_hash,classifier_version,
         reason,request_revision,priority,attempts,requested_at,next_attempt_at,last_error)
    VALUES (NEW.id,coalesce(NEW.subject,''),'','','pending','',false,'','','',1,0,0,clock_timestamp(),clock_timestamp(),'')
    ON CONFLICT (deal_id) DO UPDATE SET
        input_title=EXCLUDED.input_title,request_revision=c.request_revision+1,
        category=CASE WHEN c.manual_override THEN c.category ELSE '' END,
        candidate='',status=CASE WHEN c.manual_override THEN c.status ELSE 'pending' END,
        source=CASE WHEN c.manual_override THEN c.source ELSE '' END,
        reason=CASE WHEN c.manual_override THEN c.reason ELSE '' END,
        classified_at=CASE WHEN c.manual_override THEN c.classified_at ELSE NULL END,
        priority=0,attempts=0,requested_at=clock_timestamp(),next_attempt_at=clock_timestamp(),lease_until=NULL,last_error='';
    PERFORM pg_notify('geteverything_category_requests','');
    RETURN NEW;
END;
$$;
CREATE TRIGGER deals_classification_request AFTER INSERT OR UPDATE OF subject ON public.deals
FOR EACH ROW EXECUTE FUNCTION public.enqueue_deal_classification();
""",
            reverse_sql="""DROP TRIGGER deals_classification_request ON public.deals;
DROP FUNCTION public.enqueue_deal_classification();""",
)


class Migration(migrations.Migration):
    dependencies = [
        ('deals', '0008_thumbnail_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'classification_state',
            },
        ),
        migrations.CreateModel(
            name='DealClassification',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='classification', serialize=False, to='deals.deal')),
                ('category', models.CharField(blank=True, choices=[('', '미분류'), ('computer', 'PC·주변기기'), ('computer.desktop', 'PC·주변기기 > 데스크톱'), ('computer.laptop', 'PC·주변기기 > 노트북'), ('computer.monitor', 'PC·주변기기 > 모니터'), ('computer.component', 'PC·주변기기 > PC 부품'), ('computer.storage', 'PC·주변기기 > 저장장치'), ('computer.peripheral', 'PC·주변기기 > 주변기기'), ('mobile', '모바일'), ('mobile.phone', '모바일 > 휴대폰'), ('mobile.tablet', '모바일 > 태블릿'), ('mobile.wearable', '모바일 > 웨어러블'), ('mobile.accessory', '모바일 > 모바일 액세서리'), ('electronics', '가전·디지털'), ('electronics.audio', '가전·디지털 > 음향기기'), ('electronics.tv', '가전·디지털 > TV'), ('electronics.cleaning', '가전·디지털 > 청소·생활가전'), ('electronics.kitchen', '가전·디지털 > 주방가전'), ('electronics.climate', '가전·디지털 > 계절가전'), ('electronics.beauty', '가전·디지털 > 이미용가전'), ('games', '게임·소프트웨어'), ('games.console', '게임·소프트웨어 > 게임기·컨트롤러'), ('games.game', '게임·소프트웨어 > 게임'), ('games.software', '게임·소프트웨어 > 소프트웨어·디지털 구독'), ('food', '식품·음료'), ('food.fresh', '식품·음료 > 신선식품'), ('food.prepared', '식품·음료 > 가공·간편식'), ('food.snack', '식품·음료 > 과자·디저트'), ('food.drink', '식품·음료 > 음료·커피'), ('food.pantry', '식품·음료 > 쌀·조미료·식재료'), ('home', '생활·주방'), ('home.cleaning', '생활·주방 > 세제·청소용품'), ('home.hygiene', '생활·주방 > 위생용품'), ('home.kitchen', '생활·주방 > 주방용품'), ('home.furniture', '생활·주방 > 가구·침구'), ('home.supplies', '생활·주방 > 생활잡화'), ('fashion', '패션·잡화'), ('fashion.clothing', '패션·잡화 > 의류'), ('fashion.shoes', '패션·잡화 > 신발'), ('fashion.accessory', '패션·잡화 > 가방·패션잡화'), ('beauty', '뷰티·건강'), ('beauty.cosmetic', '뷰티·건강 > 화장품·향수'), ('beauty.care', '뷰티·건강 > 헤어·바디케어'), ('beauty.supplement', '뷰티·건강 > 영양제'), ('beauty.health', '뷰티·건강 > 건강용품'), ('baby', '출산·육아'), ('baby.care', '출산·육아 > 육아용품'), ('baby.food', '출산·육아 > 분유·이유식'), ('pet', '반려동물'), ('pet.food', '반려동물 > 사료·간식'), ('pet.supplies', '반려동물 > 반려동물용품'), ('sports', '스포츠·레저·취미'), ('sports.outdoor', '스포츠·레저·취미 > 캠핑·레저'), ('sports.fitness', '스포츠·레저·취미 > 운동용품'), ('sports.hobby', '스포츠·레저·취미 > 취미용품'), ('services', '상품권·서비스'), ('services.voucher', '상품권·서비스 > 상품권·교환권'), ('services.travel', '상품권·서비스 > 여행·숙박·티켓'), ('services.telecom', '상품권·서비스 > 통신요금제')], default='', max_length=32, verbose_name='표준 카테고리')),
                ('candidate', models.CharField(blank=True, choices=[('', '미분류'), ('computer', 'PC·주변기기'), ('computer.desktop', 'PC·주변기기 > 데스크톱'), ('computer.laptop', 'PC·주변기기 > 노트북'), ('computer.monitor', 'PC·주변기기 > 모니터'), ('computer.component', 'PC·주변기기 > PC 부품'), ('computer.storage', 'PC·주변기기 > 저장장치'), ('computer.peripheral', 'PC·주변기기 > 주변기기'), ('mobile', '모바일'), ('mobile.phone', '모바일 > 휴대폰'), ('mobile.tablet', '모바일 > 태블릿'), ('mobile.wearable', '모바일 > 웨어러블'), ('mobile.accessory', '모바일 > 모바일 액세서리'), ('electronics', '가전·디지털'), ('electronics.audio', '가전·디지털 > 음향기기'), ('electronics.tv', '가전·디지털 > TV'), ('electronics.cleaning', '가전·디지털 > 청소·생활가전'), ('electronics.kitchen', '가전·디지털 > 주방가전'), ('electronics.climate', '가전·디지털 > 계절가전'), ('electronics.beauty', '가전·디지털 > 이미용가전'), ('games', '게임·소프트웨어'), ('games.console', '게임·소프트웨어 > 게임기·컨트롤러'), ('games.game', '게임·소프트웨어 > 게임'), ('games.software', '게임·소프트웨어 > 소프트웨어·디지털 구독'), ('food', '식품·음료'), ('food.fresh', '식품·음료 > 신선식품'), ('food.prepared', '식품·음료 > 가공·간편식'), ('food.snack', '식품·음료 > 과자·디저트'), ('food.drink', '식품·음료 > 음료·커피'), ('food.pantry', '식품·음료 > 쌀·조미료·식재료'), ('home', '생활·주방'), ('home.cleaning', '생활·주방 > 세제·청소용품'), ('home.hygiene', '생활·주방 > 위생용품'), ('home.kitchen', '생활·주방 > 주방용품'), ('home.furniture', '생활·주방 > 가구·침구'), ('home.supplies', '생활·주방 > 생활잡화'), ('fashion', '패션·잡화'), ('fashion.clothing', '패션·잡화 > 의류'), ('fashion.shoes', '패션·잡화 > 신발'), ('fashion.accessory', '패션·잡화 > 가방·패션잡화'), ('beauty', '뷰티·건강'), ('beauty.cosmetic', '뷰티·건강 > 화장품·향수'), ('beauty.care', '뷰티·건강 > 헤어·바디케어'), ('beauty.supplement', '뷰티·건강 > 영양제'), ('beauty.health', '뷰티·건강 > 건강용품'), ('baby', '출산·육아'), ('baby.care', '출산·육아 > 육아용품'), ('baby.food', '출산·육아 > 분유·이유식'), ('pet', '반려동물'), ('pet.food', '반려동물 > 사료·간식'), ('pet.supplies', '반려동물 > 반려동물용품'), ('sports', '스포츠·레저·취미'), ('sports.outdoor', '스포츠·레저·취미 > 캠핑·레저'), ('sports.fitness', '스포츠·레저·취미 > 운동용품'), ('sports.hobby', '스포츠·레저·취미 > 취미용품'), ('services', '상품권·서비스'), ('services.voucher', '상품권·서비스 > 상품권·교환권'), ('services.travel', '상품권·서비스 > 여행·숙박·티켓'), ('services.telecom', '상품권·서비스 > 통신요금제')], default='', max_length=32, verbose_name='모델 제안')),
                ('status', models.CharField(choices=[('pending', '규칙 분류 대기'), ('llm', '모델 분류 대기'), ('ready', '분류 완료'), ('review', '검토 필요'), ('error', '처리 실패')], default='pending', max_length=16, verbose_name='처리 상태')),
                ('source', models.CharField(blank=True, choices=[('', '미분류'), ('rule', '상품 규칙'), ('llm', '로컬 모델'), ('manual', '수동 지정')], default='', max_length=16, verbose_name='분류 방식')),
                ('manual_override', models.BooleanField(default=False, verbose_name='수동 분류 유지')),
                ('input_title', models.CharField(blank=True, default='', max_length=512, verbose_name='분류 대상 제목')),
                ('title_hash', models.CharField(blank=True, default='', max_length=64)),
                ('classifier_version', models.CharField(blank=True, default='', max_length=160, verbose_name='분류기 버전')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='분류 근거')),
                ('request_revision', models.BigIntegerField(default=1)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='재시도 횟수')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='요청 시각')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('classified_at', models.DateTimeField(blank=True, null=True, verbose_name='분류 시각')),
                ('last_error', models.CharField(blank=True, default='', max_length=120, verbose_name='오류')),
            ],
            options={
                'verbose_name': '게시물 표준 분류',
                'verbose_name_plural': '게시물 표준 분류',
                'db_table': 'deal_classifications',
                'indexes': [models.Index(fields=['status', 'priority', 'next_attempt_at'], name='classification_due'), models.Index(fields=['category'], name='classification_category'), models.Index(fields=['title_hash', 'classifier_version'], name='classification_cache')],
            },
        ),
        REQUEST_TRIGGER,
    ]
