# Generated by Django 5.1 on 2026-09-18 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


REQUEST_TRIGGER = migrations.RunSQL(
    sql="""
CREATE FUNCTION public.enqueue_deal_measurements() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$
BEGIN
    IF TG_OP='UPDATE' AND
       ROW(NEW.subject,NEW.price,NEW.currency,NEW.delivery_price,NEW.numeric_evidence)
       IS NOT DISTINCT FROM ROW(OLD.subject,OLD.price,OLD.currency,OLD.delivery_price,OLD.numeric_evidence)
    THEN RETURN NEW; END IF;
    INSERT INTO public.deal_measurements AS m
       (deal_id,input,result,status,parser_version,request_revision,priority,requested_at,last_error)
    VALUES (NEW.id,jsonb_build_object('subject',coalesce(NEW.subject,''),'price',NEW.price,
        'currency',NEW.currency,'delivery_price',NEW.delivery_price,'numeric_evidence',coalesce(NEW.numeric_evidence,'{}'::jsonb)),
        '{}'::jsonb,'pending','',1,0,clock_timestamp(),'')
    ON CONFLICT (deal_id) DO UPDATE SET
       input=EXCLUDED.input,result='{}'::jsonb,status='pending',request_revision=m.request_revision+1,
       priority=0,requested_at=clock_timestamp(),processed_at=NULL,lease_until=NULL,last_error='';
    RETURN NEW;
END;
$$;
CREATE TRIGGER deals_measurements_request AFTER INSERT OR UPDATE OF subject,price,currency,delivery_price,numeric_evidence ON public.deals
FOR EACH ROW EXECUTE FUNCTION public.enqueue_deal_measurements();
""",
    reverse_sql="""DROP TRIGGER deals_measurements_request ON public.deals;
DROP FUNCTION public.enqueue_deal_measurements();""",
)


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_deal_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='numeric_evidence',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='수집 가격 원문'),
        ),
        migrations.CreateModel(
            name='DealMeasurements',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='measurements', serialize=False, to='deals.deal')),
                ('input', models.JSONField(default=dict, verbose_name='분석 입력')),
                ('result', models.JSONField(default=dict, verbose_name='계산 결과')),
                ('status', models.CharField(choices=[('pending', '계산 대기'), ('ready', '단가 계산 완료'), ('partial', '정보 일부 확인'), ('review', '계산 보류'), ('error', '처리 실패')], default='pending', max_length=16, verbose_name='처리 상태')),
                ('parser_version', models.CharField(blank=True, default='', max_length=32, verbose_name='계산기 버전')),
                ('request_revision', models.BigIntegerField(default=1)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='요청 시각')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='계산 시각')),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=120, verbose_name='오류')),
            ],
            options={
                'verbose_name': '상품 수량·단가',
                'verbose_name_plural': '상품 수량·단가',
                'db_table': 'deal_measurements',
                'indexes': [models.Index(fields=['status', 'priority', 'lease_until'], name='measurements_due')],
            },
        ),
        REQUEST_TRIGGER,
    ]
