from django.db import migrations, models


CHOICES = [('', '미분류'), ('computer', 'PC·주변기기'), ('computer.desktop', 'PC·주변기기 > 데스크톱'), ('computer.laptop', 'PC·주변기기 > 노트북'), ('computer.monitor', 'PC·주변기기 > 모니터'), ('computer.component', 'PC·주변기기 > PC 부품'), ('computer.storage', 'PC·주변기기 > 저장장치'), ('computer.peripheral', 'PC·주변기기 > 주변기기'), ('mobile', '모바일'), ('mobile.phone', '모바일 > 휴대폰'), ('mobile.tablet', '모바일 > 태블릿'), ('mobile.wearable', '모바일 > 웨어러블'), ('mobile.accessory', '모바일 > 모바일 액세서리'), ('electronics', '가전·디지털'), ('electronics.audio', '가전·디지털 > 음향기기'), ('electronics.tv', '가전·디지털 > TV'), ('electronics.cleaning', '가전·디지털 > 청소·생활가전'), ('electronics.kitchen', '가전·디지털 > 주방가전'), ('electronics.climate', '가전·디지털 > 계절가전'), ('electronics.beauty', '가전·디지털 > 이미용가전'), ('electronics.camera', '가전·디지털 > 카메라·촬영기기'), ('electronics.tool', '가전·디지털 > 전동공구'), ('games', '게임·소프트웨어'), ('games.console', '게임·소프트웨어 > 게임기·컨트롤러'), ('games.game', '게임·소프트웨어 > 게임'), ('games.software', '게임·소프트웨어 > 소프트웨어·디지털 구독'), ('food', '식품·음료'), ('food.fresh', '식품·음료 > 신선식품'), ('food.prepared', '식품·음료 > 가공·간편식'), ('food.snack', '식품·음료 > 과자·디저트'), ('food.drink', '식품·음료 > 음료·커피'), ('food.pantry', '식품·음료 > 쌀·조미료·식재료'), ('home', '생활·주방'), ('home.cleaning', '생활·주방 > 세제·청소용품'), ('home.hygiene', '생활·주방 > 위생용품'), ('home.kitchen', '생활·주방 > 주방용품'), ('home.furniture', '생활·주방 > 가구·침구'), ('home.supplies', '생활·주방 > 생활잡화'), ('home.garden', '생활·주방 > 꽃·원예'), ('home.lighting', '생활·주방 > 조명'), ('fashion', '패션·잡화'), ('fashion.clothing', '패션·잡화 > 의류'), ('fashion.shoes', '패션·잡화 > 신발'), ('fashion.accessory', '패션·잡화 > 가방·패션잡화'), ('beauty', '뷰티·건강'), ('beauty.cosmetic', '뷰티·건강 > 화장품·향수'), ('beauty.care', '뷰티·건강 > 헤어·바디케어'), ('beauty.supplement', '뷰티·건강 > 영양제'), ('beauty.health', '뷰티·건강 > 건강용품'), ('baby', '출산·육아'), ('baby.care', '출산·육아 > 육아용품'), ('baby.food', '출산·육아 > 분유·이유식'), ('pet', '반려동물'), ('pet.food', '반려동물 > 사료·간식'), ('pet.supplies', '반려동물 > 반려동물용품'), ('sports', '스포츠·레저·취미'), ('sports.outdoor', '스포츠·레저·취미 > 캠핑·레저'), ('sports.fitness', '스포츠·레저·취미 > 운동용품'), ('sports.hobby', '스포츠·레저·취미 > 취미용품'), ('auto', '자동차·차량용품'), ('auto.care', '자동차·차량용품 > 차량 관리·정비'), ('auto.accessory', '자동차·차량용품 > 차량 액세서리'), ('auto.device', '자동차·차량용품 > 차량 전자기기'), ('culture', '도서·문화'), ('culture.books', '도서·문화 > 도서·전자책'), ('culture.video', '도서·문화 > 영화·영상'), ('culture.music', '도서·문화 > 음반·음악'), ('services', '상품권·혜택·서비스'), ('services.voucher', '상품권·혜택·서비스 > 상품권·교환권'), ('services.travel', '상품권·혜택·서비스 > 여행·숙박·티켓'), ('services.telecom', '상품권·혜택·서비스 > 통신요금제'), ('services.coupon', '상품권·혜택·서비스 > 할인쿠폰'), ('services.points', '상품권·혜택·서비스 > 포인트·적립'), ('services.event', '상품권·혜택·서비스 > 응모·증정 행사'), ('services.promotion', '상품권·혜택·서비스 > 쇼핑 할인행사'), ('services.membership', '상품권·혜택·서비스 > 멤버십·이용 서비스'), ('services.education', '상품권·혜택·서비스 > 교육·강좌'), ('services.finance', '상품권·혜택·서비스 > 금융·보험 혜택')]
TRIGGER_SQL = "\nCREATE OR REPLACE FUNCTION public.enqueue_deal_classification() RETURNS trigger\nLANGUAGE plpgsql SET search_path=pg_catalog,public AS $$\nBEGIN\n    IF TG_OP='UPDATE' AND ROW(NEW.subject,NEW.community_name,NEW.category,NEW.shop_name,NEW.shop_url_1,NEW.shop_url_2)\n        IS NOT DISTINCT FROM ROW(OLD.subject,OLD.community_name,OLD.category,OLD.shop_name,OLD.shop_url_1,OLD.shop_url_2)\n        THEN RETURN NEW; END IF;\n    INSERT INTO public.deal_classifications AS c\n        (deal_id,input_title,category,candidate,status,source,manual_override,title_hash,classifier_version,\n         reason,request_revision,priority,attempts,requested_at,next_attempt_at,last_error)\n    VALUES (NEW.id,coalesce(NEW.subject,''),'','','pending','',false,'','','',1,0,0,clock_timestamp(),clock_timestamp(),'')\n    ON CONFLICT (deal_id) DO UPDATE SET\n        input_title=EXCLUDED.input_title,request_revision=c.request_revision+1,\n        category=CASE WHEN c.manual_override THEN c.category ELSE '' END,\n        candidate='',status=CASE WHEN c.manual_override THEN c.status ELSE 'pending' END,\n        source=CASE WHEN c.manual_override THEN c.source ELSE '' END,\n        reason=CASE WHEN c.manual_override THEN c.reason ELSE '' END,\n        classified_at=CASE WHEN c.manual_override THEN c.classified_at ELSE NULL END,\n        priority=0,attempts=0,requested_at=clock_timestamp(),next_attempt_at=clock_timestamp(),lease_until=NULL,last_error='';\n    PERFORM pg_notify('geteverything_category_requests','');\n    RETURN NEW;\nEND;\n$$;\nDROP TRIGGER deals_classification_request ON public.deals;\nCREATE TRIGGER deals_classification_request AFTER INSERT OR UPDATE OF subject,community_name,category,shop_name,shop_url_1,shop_url_2 ON public.deals\nFOR EACH ROW EXECUTE FUNCTION public.enqueue_deal_classification();\n"
REVERSE_TRIGGER_SQL = "\nCREATE OR REPLACE FUNCTION public.enqueue_deal_classification() RETURNS trigger\nLANGUAGE plpgsql SET search_path=pg_catalog,public AS $$\nBEGIN\n    IF TG_OP='UPDATE' AND NEW.subject IS NOT DISTINCT FROM OLD.subject THEN RETURN NEW; END IF;\n    INSERT INTO public.deal_classifications AS c\n        (deal_id,input_title,category,candidate,status,source,manual_override,title_hash,classifier_version,\n         reason,request_revision,priority,attempts,requested_at,next_attempt_at,last_error)\n    VALUES (NEW.id,coalesce(NEW.subject,''),'','','pending','',false,'','','',1,0,0,clock_timestamp(),clock_timestamp(),'')\n    ON CONFLICT (deal_id) DO UPDATE SET\n        input_title=EXCLUDED.input_title,request_revision=c.request_revision+1,\n        category=CASE WHEN c.manual_override THEN c.category ELSE '' END,\n        candidate='',status=CASE WHEN c.manual_override THEN c.status ELSE 'pending' END,\n        source=CASE WHEN c.manual_override THEN c.source ELSE '' END,\n        reason=CASE WHEN c.manual_override THEN c.reason ELSE '' END,\n        classified_at=CASE WHEN c.manual_override THEN c.classified_at ELSE NULL END,\n        priority=0,attempts=0,requested_at=clock_timestamp(),next_attempt_at=clock_timestamp(),lease_until=NULL,last_error='';\n    PERFORM pg_notify('geteverything_category_requests','');\n    RETURN NEW;\nEND;\n$$;\nDROP TRIGGER deals_classification_request ON public.deals;\nCREATE TRIGGER deals_classification_request AFTER INSERT OR UPDATE OF subject ON public.deals\nFOR EACH ROW EXECUTE FUNCTION public.enqueue_deal_classification();\n"


class Migration(migrations.Migration):
    dependencies = [('deals', '0010_deal_measurements')]
    operations = [
        migrations.AlterField(model_name='dealclassification', name='category', field=models.CharField(blank=True, choices=CHOICES, default='', max_length=32, verbose_name='표준 카테고리')),
        migrations.AlterField(model_name='dealclassification', name='candidate', field=models.CharField(blank=True, choices=CHOICES, default='', max_length=32, verbose_name='모델 제안')),
        migrations.RunSQL(TRIGGER_SQL, REVERSE_TRIGGER_SQL),
    ]
