# Generated by Django 5.1 on 2026-09-19 02:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


REQUEST_TRIGGER = migrations.RunSQL(
    sql="""
CREATE FUNCTION public.enqueue_deal_product() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$
DECLARE assignment public.deal_products%ROWTYPE;
BEGIN
    IF TG_OP='UPDATE' AND
       ROW(NEW.subject,NEW.price,NEW.currency,NEW.delivery_price,NEW.numeric_evidence)
       IS NOT DISTINCT FROM ROW(OLD.subject,OLD.price,OLD.currency,OLD.delivery_price,OLD.numeric_evidence)
    THEN RETURN NEW; END IF;
    INSERT INTO public.deal_products AS p
       (deal_id,input_title,extraction,candidates,status,source,manual_override,input_hash,
        processor_version,request_revision,identity_revision,price_revision,priority,
        requested_at,next_attempt_at,attempts,last_error)
    VALUES (NEW.id,coalesce(NEW.subject,''),'{}'::jsonb,'[]'::jsonb,'pending','',false,'',
        '',1,1,1,0,clock_timestamp(),clock_timestamp(),0,'')
    ON CONFLICT (deal_id) DO UPDATE SET
       input_title=EXCLUDED.input_title,price_revision=p.price_revision+1,
       identity_revision=p.identity_revision+CASE WHEN p.input_title<>EXCLUDED.input_title THEN 1 ELSE 0 END,
       request_revision=p.request_revision+CASE WHEN p.input_title<>EXCLUDED.input_title THEN 1 ELSE 0 END,
       status=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.status
                   WHEN p.manual_override THEN 'review' ELSE 'pending' END,
       product_id=CASE WHEN p.input_title=EXCLUDED.input_title OR p.manual_override THEN p.product_id ELSE NULL END,
       extraction=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.extraction ELSE '{}'::jsonb END,
       candidates=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.candidates ELSE '[]'::jsonb END,
       source=CASE WHEN p.input_title=EXCLUDED.input_title OR p.manual_override THEN p.source ELSE '' END,
       input_hash=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.input_hash ELSE '' END,
       processor_version=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.processor_version ELSE '' END,
       lease_until=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.lease_until ELSE NULL END,
       processed_at=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.processed_at ELSE NULL END,
       priority=0,requested_at=clock_timestamp(),next_attempt_at=clock_timestamp(),
       attempts=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.attempts ELSE 0 END,
       last_error=CASE WHEN p.input_title=EXCLUDED.input_title THEN p.last_error
                       WHEN p.manual_override THEN 'title_changed_reconfirm' ELSE '' END
    RETURNING * INTO assignment;
    INSERT INTO public.product_prices
       (deal_id,product_id,identity_revision,price_revision,published_at,observed_at,is_backfill,input,result)
    VALUES (NEW.id,CASE WHEN assignment.status='ready' THEN assignment.product_id ELSE NULL END,
        assignment.identity_revision,assignment.price_revision,coalesce(NEW.write_at,NEW.create_at,clock_timestamp()),
        clock_timestamp(),false,jsonb_build_object('subject',coalesce(NEW.subject,''),'price',NEW.price,
        'currency',NEW.currency,'delivery_price',NEW.delivery_price,'numeric_evidence',coalesce(NEW.numeric_evidence,'{}'::jsonb)),
        '{}'::jsonb);
    RETURN NEW;
END;
$$;
CREATE TRIGGER deals_product_request AFTER INSERT OR UPDATE OF subject,price,currency,delivery_price,numeric_evidence ON public.deals
FOR EACH ROW EXECUTE FUNCTION public.enqueue_deal_product();
""",
    reverse_sql="""DROP TRIGGER deals_product_request ON public.deals;
DROP FUNCTION public.enqueue_deal_product();""",
)


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_classification_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMatcherVersion',
            fields=[
                ('version', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('weights', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('example_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '상품 매칭 학습 결과',
                'verbose_name_plural': '상품 매칭 학습 결과',
                'db_table': 'product_matcher_versions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=240, verbose_name='상품명')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='브랜드')),
                ('model', models.CharField(blank=True, default='', max_length=120, verbose_name='모델')),
                ('attributes', models.JSONField(default=dict, verbose_name='규격·옵션')),
                ('category', models.CharField(blank=True, choices=[('', '미분류'), ('computer', 'PC·주변기기'), ('computer.desktop', 'PC·주변기기 > 데스크톱'), ('computer.laptop', 'PC·주변기기 > 노트북'), ('computer.monitor', 'PC·주변기기 > 모니터'), ('computer.component', 'PC·주변기기 > PC 부품'), ('computer.storage', 'PC·주변기기 > 저장장치'), ('computer.peripheral', 'PC·주변기기 > 주변기기'), ('mobile', '모바일'), ('mobile.phone', '모바일 > 휴대폰'), ('mobile.tablet', '모바일 > 태블릿'), ('mobile.wearable', '모바일 > 웨어러블'), ('mobile.accessory', '모바일 > 모바일 액세서리'), ('electronics', '가전·디지털'), ('electronics.audio', '가전·디지털 > 음향기기'), ('electronics.tv', '가전·디지털 > TV'), ('electronics.cleaning', '가전·디지털 > 청소·생활가전'), ('electronics.kitchen', '가전·디지털 > 주방가전'), ('electronics.climate', '가전·디지털 > 계절가전'), ('electronics.beauty', '가전·디지털 > 이미용가전'), ('electronics.camera', '가전·디지털 > 카메라·촬영기기'), ('electronics.tool', '가전·디지털 > 전동공구'), ('games', '게임·소프트웨어'), ('games.console', '게임·소프트웨어 > 게임기·컨트롤러'), ('games.game', '게임·소프트웨어 > 게임'), ('games.software', '게임·소프트웨어 > 소프트웨어·디지털 구독'), ('food', '식품·음료'), ('food.fresh', '식품·음료 > 신선식품'), ('food.prepared', '식품·음료 > 가공·간편식'), ('food.snack', '식품·음료 > 과자·디저트'), ('food.drink', '식품·음료 > 음료·커피'), ('food.pantry', '식품·음료 > 쌀·조미료·식재료'), ('home', '생활·주방'), ('home.cleaning', '생활·주방 > 세제·청소용품'), ('home.hygiene', '생활·주방 > 위생용품'), ('home.kitchen', '생활·주방 > 주방용품'), ('home.furniture', '생활·주방 > 가구·침구'), ('home.supplies', '생활·주방 > 생활잡화'), ('home.garden', '생활·주방 > 꽃·원예'), ('home.lighting', '생활·주방 > 조명'), ('fashion', '패션·잡화'), ('fashion.clothing', '패션·잡화 > 의류'), ('fashion.shoes', '패션·잡화 > 신발'), ('fashion.accessory', '패션·잡화 > 가방·패션잡화'), ('beauty', '뷰티·건강'), ('beauty.cosmetic', '뷰티·건강 > 화장품·향수'), ('beauty.care', '뷰티·건강 > 헤어·바디케어'), ('beauty.supplement', '뷰티·건강 > 영양제'), ('beauty.health', '뷰티·건강 > 건강용품'), ('baby', '출산·육아'), ('baby.care', '출산·육아 > 육아용품'), ('baby.food', '출산·육아 > 분유·이유식'), ('pet', '반려동물'), ('pet.food', '반려동물 > 사료·간식'), ('pet.supplies', '반려동물 > 반려동물용품'), ('sports', '스포츠·레저·취미'), ('sports.outdoor', '스포츠·레저·취미 > 캠핑·레저'), ('sports.fitness', '스포츠·레저·취미 > 운동용품'), ('sports.hobby', '스포츠·레저·취미 > 취미용품'), ('auto', '자동차·차량용품'), ('auto.care', '자동차·차량용품 > 차량 관리·정비'), ('auto.accessory', '자동차·차량용품 > 차량 액세서리'), ('auto.device', '자동차·차량용품 > 차량 전자기기'), ('culture', '도서·문화'), ('culture.books', '도서·문화 > 도서·전자책'), ('culture.video', '도서·문화 > 영화·영상'), ('culture.music', '도서·문화 > 음반·음악'), ('services', '상품권·혜택·서비스'), ('services.voucher', '상품권·혜택·서비스 > 상품권·교환권'), ('services.travel', '상품권·혜택·서비스 > 여행·숙박·티켓'), ('services.telecom', '상품권·혜택·서비스 > 통신요금제'), ('services.coupon', '상품권·혜택·서비스 > 할인쿠폰'), ('services.points', '상품권·혜택·서비스 > 포인트·적립'), ('services.event', '상품권·혜택·서비스 > 응모·증정 행사'), ('services.promotion', '상품권·혜택·서비스 > 쇼핑 할인행사'), ('services.membership', '상품권·혜택·서비스 > 멤버십·이용 서비스'), ('services.education', '상품권·혜택·서비스 > 교육·강좌'), ('services.finance', '상품권·혜택·서비스 > 금융·보험 혜택')], default='', max_length=32, verbose_name='표준 카테고리')),
                ('verified', models.BooleanField(default=False, verbose_name='운영자 확인')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '고유 상품',
                'verbose_name_plural': '고유 상품',
                'db_table': 'products',
                'indexes': [models.Index(fields=['brand', 'model'], name='product_brand_model')],
            },
        ),
        migrations.CreateModel(
            name='ProductMatchExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(max_length=512, verbose_name='게시물 제목')),
                ('right_title', models.CharField(max_length=512, verbose_name='비교 상품명')),
                ('same_product', models.BooleanField(verbose_name='동일 상품')),
                ('extraction', models.JSONField(default=dict)),
                ('origin', models.CharField(choices=[('operator', '운영자 확인'), ('bootstrap_review', '초기 검토 예제')], default='operator', max_length=32, verbose_name='확인 출처')),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('example_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deals.product')),
            ],
            options={
                'verbose_name': '상품 연결 학습 예제',
                'verbose_name_plural': '상품 연결 학습 예제',
                'db_table': 'product_match_examples',
            },
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product_assignment', serialize=False, to='deals.deal')),
                ('input_title', models.CharField(blank=True, default='', max_length=512, verbose_name='입력 제목')),
                ('extraction', models.JSONField(default=dict, verbose_name='추출한 상품 정보')),
                ('candidates', models.JSONField(default=list, verbose_name='유사 상품 제안')),
                ('status', models.CharField(choices=[('pending', '상품 분석 대기'), ('llm', '모델 추출 대기'), ('ready', '연결 완료'), ('review', '연결 확인 필요'), ('error', '처리 실패')], default='pending', max_length=16, verbose_name='상태')),
                ('source', models.CharField(blank=True, choices=[('', '미처리'), ('rule', '모델명·규격 규칙'), ('llm', '로컬 모델'), ('learned', '학습된 연결'), ('manual', '수동 연결')], default='', max_length=16, verbose_name='처리 방식')),
                ('manual_override', models.BooleanField(default=False, verbose_name='수동 연결 유지')),
                ('input_hash', models.CharField(blank=True, default='', max_length=64)),
                ('processor_version', models.CharField(blank=True, default='', max_length=160, verbose_name='처리 버전')),
                ('request_revision', models.BigIntegerField(default=1)),
                ('identity_revision', models.BigIntegerField(default=1)),
                ('price_revision', models.BigIntegerField(default=1)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시각')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=160, verbose_name='처리 사유')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='deals.product', verbose_name='연결 상품')),
            ],
            options={
                'verbose_name': '게시물 상품 연결',
                'verbose_name_plural': '게시물 상품 연결',
                'db_table': 'deal_products',
                'indexes': [models.Index(fields=['status', 'priority', 'next_attempt_at'], name='product_job_due'), models.Index(fields=['input_hash', 'processor_version'], name='product_extraction_cache')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_revision', models.BigIntegerField()),
                ('price_revision', models.BigIntegerField()),
                ('published_at', models.DateTimeField(verbose_name='게시물 작성일')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가격 확인 시각')),
                ('is_backfill', models.BooleanField(default=False)),
                ('input', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='deals.deal')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='deals.product')),
            ],
            options={
                'db_table': 'product_prices',
                'indexes': [models.Index(fields=['product', 'published_at', 'id'], name='product_price_timeline'), models.Index(fields=['processed_at', 'id'], name='product_price_pending')],
                'constraints': [models.UniqueConstraint(fields=('deal', 'price_revision'), name='product_price_revision_unique')],
            },
        ),
        REQUEST_TRIGGER,
    ]
