# Generated by Django 5.1 on 2026-09-20 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


SOURCE_TRIGGER = migrations.RunSQL("""
CREATE FUNCTION public.enqueue_product_source() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$
BEGIN
    IF TG_OP='UPDATE' AND ROW(NEW.subject,NEW.shop_url_1,NEW.shop_url_2)
       IS NOT DISTINCT FROM ROW(OLD.subject,OLD.shop_url_1,OLD.shop_url_2)
    THEN RETURN NEW; END IF;
    INSERT INTO public.product_sources AS s
        (deal_id,input,revision,status,priority,attempts,requested_at,next_attempt_at,processed_at,last_error)
    VALUES (NEW.id,jsonb_build_object('title',coalesce(NEW.subject,''),
        'urls',jsonb_build_array(coalesce(NEW.shop_url_1,''),coalesce(NEW.shop_url_2,''))),
        1,'pending',0,0,clock_timestamp(),clock_timestamp(),NULL,'')
    ON CONFLICT (deal_id) DO UPDATE SET input=EXCLUDED.input,revision=s.revision+1,
        status='pending',priority=0,attempts=0,requested_at=clock_timestamp(),next_attempt_at=clock_timestamp(),
        processed_at=NULL,last_error='';
    RETURN NEW;
END;
$$;
CREATE TRIGGER deals_product_source_request
AFTER INSERT OR UPDATE OF subject,shop_url_1,shop_url_2 ON public.deals
FOR EACH ROW EXECUTE FUNCTION public.enqueue_product_source();
""", """
DROP TRIGGER deals_product_source_request ON public.deals;
DROP FUNCTION public.enqueue_product_source();
""")


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_deal_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealproduct',
            name='source',
            field=models.CharField(blank=True, choices=[('', '미처리'), ('rule', '모델명·규격 규칙'), ('llm', '로컬 모델'), ('learned', '학습된 연결'), ('manual', '수동 연결'), ('identifier', '쇼핑몰 상품번호')], default='', max_length=16, verbose_name='처리 방식'),
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product_source', serialize=False, to='deals.deal')),
                ('input', models.JSONField(default=dict)),
                ('revision', models.BigIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=160)),
            ],
            options={
                'db_table': 'product_sources',
                'indexes': [models.Index(fields=['status', 'priority', 'next_attempt_at'], name='product_sources_due')],
            },
        ),
        migrations.CreateModel(
            name='ProductReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('namespace', models.CharField(max_length=40)),
                ('scope', models.CharField(blank=True, default='', max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('canonical_url', models.URLField(max_length=512)),
                ('evidence', models.CharField(default='url', max_length=16)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='deals.productsource')),
            ],
            options={
                'db_table': 'product_references',
                'constraints': [models.UniqueConstraint(fields=('source', 'key'), name='product_reference_unique')],
            },
        ),
        SOURCE_TRIGGER,
    ]
