# Generated by Django 5.1 on 2025-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver')], max_length=64),
        ),
    ]
