# Generated by Django 5.1 on 2025-03-23 04:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_kakao_id_user_refresh_token_alter_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('7e432c23-b57d-4927-bf00-2052eaf2b9f0'), max_length=255, unique=True),
        ),
    ]
