# Generated by Django 5.1 on 2025-03-23 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_email_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('32941252-8850-4a26-b0d6-bc5021dee843'), max_length=255, unique=True),
        ),
    ]
