# Generated by Django 5.1 on 2025-03-23 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token_expire_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token_expire_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('5860ecb1-ba63-481b-a268-d05a6116878e'), max_length=255, unique=True),
        ),
    ]
