# Generated by Django 5.1 on 2025-03-23 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_access_token_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('fb0b7604-e231-4eaa-a235-f4856773b418'), max_length=255, unique=True),
        ),
    ]
