# Generated by Django 5.1 on 2025-05-01 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_social_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('b478852c-ffd8-4de7-9d03-43346842cdc3'), max_length=255, unique=True),
        ),
    ]
