# Generated by Django 5.1 on 2025-05-02 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('76fbb254-84e0-47a1-87e8-ea2a1722b773'), max_length=255, unique=True),
        ),
    ]
