# Generated by Django 5.1 on 2025-05-02 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_authenticated_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('1d7050b5-c594-44ae-964d-bc1592ae7829'), max_length=255, unique=True),
        ),
    ]
