# Generated by Django 5.1 on 2025-05-02 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('ec3813d4-f8bb-44bf-8f7e-d135b6e0fe3c'), max_length=255, unique=True),
        ),
    ]
