# Generated by Django 5.1 on 2025-12-10 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('154d90eb-333d-4526-b924-0e1ddb48cc22'), max_length=255, unique=True),
        ),
    ]
