# Generated by Django 5.1 on 2025-12-10 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('f99d7458-80bd-42f2-99a9-872a8dc6530a'), max_length=255, unique=True),
        ),
    ]
