# Generated by Django 5.1 on 2025-12-10 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('86214d7e-a3c1-41a4-b255-8be976cdec77'), max_length=255, unique=True),
        ),
    ]
