# Generated by Django 5.1 on 2025-12-10 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('9c5a5e29-ac28-4b38-9fe2-774442fbe22b'), max_length=255, unique=True),
        ),
    ]
