# Generated by Django 5.1 on 2025-12-10 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('b6134920-d730-4a9e-8d27-24a5e6dc331e'), max_length=255, unique=True),
        ),
    ]
