# Generated by Django 5.1 on 2025-12-13 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('9d54ba40-8cff-4d42-ba51-c9330d36252c'), max_length=255, unique=True),
        ),
    ]
